### ISSUE TITLE
JWT support in this bundle?

### ISSUE THREAD

**Issue by duanegran** [bshaffer/oauth2-server-bundle#69]
In the OAuth2 server that this based on it appears to support JWT tokens (http://bshaffer.github.io/oauth2-server-php-docs/overview/jwt-access-tokens/) but I don't see how to utilize this with the Symfony bundle.  Is there some way in the tokenAction() for the TokenController to do this?

**Comment by vroad** [comment]
@duanegran Seems possible by adding this to config.yml:
```yml
parameters:
  oauth2.server.config:
    use_jwt_access_tokens: true
    issuer: https://www.acme.com
  oauth2.storage.public_key.class: Acme\AuthBundle\Storage\PublicKey
```

This bundle lacks command and storage for storing public/private key, so you need to create them by yourself.
Authorization code storage is not used with this config. Probably because generated JWT token contains all information you need. (You can extract information from JWT by decoding with the public key)
